In [44]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [45]:
df = pd.read_csv('Social_Network_Ads.csv')
df

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   User ID          400 non-null    int64
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64
 3   EstimatedSalary  400 non-null    int64
 4   Purchased        400 non-null    int64
dtypes: int64(4), object(1)
memory usage: 15.8+ KB

In [47]:
df.head(1)

    User ID Gender  Age  EstimatedSalary  Purchased
0  15624510   Male   19            19000          0

In [48]:
df.sample(5)

      User ID  Gender  Age  EstimatedSalary  Purchased
383  15707634    Male   49            28000          1
343  15629739  Female   47            51000          1
219  15732987    Male   59           143000          1
40   15764419  Female   27            17000          0
220  15789432  Female   41            80000          0

In [49]:
df.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [50]:
df=df.iloc[:,2:]

In [51]:
df

     Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [52]:
from sklearn.model_selection import train_test_split

In [53]:
X_train, X_test, y_train, y_test = train_test_split(df.drop('Purchased', axis=1), df['Purchased'], test_size = 0.3, random_state = 0)

In [54]:
df

     Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [55]:
X_train.shape, X_test.shape

((280, 2), (120, 2))

In [56]:
# NOW USE STANDARDIZATION

In [57]:
from sklearn.preprocessing import StandardScaler

In [58]:
scaler = StandardScaler()

In [59]:
scaler.fit(X_train)

StandardScaler()

In [60]:
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [61]:
scaler.mean_

array([3.78642857e+01, 6.98071429e+04])

In [62]:
X_train

     Age  EstimatedSalary
92    26            15000
223   60           102000
234   38           112000
232   40           107000
377   42            53000
..   ...              ...
323   48            30000
192   29            43000
117   36            52000
47    27            54000
172   26           118000

[280 rows x 2 columns]

In [64]:
X_train_scaled = pd.DataFrame(X_train_scaled, columns=X_train.columns)

In [66]:
X_train_scaled

          Age  EstimatedSalary
0   -1.163172        -1.584970
1    2.170181         0.930987
2    0.013305         1.220177
3    0.209385         1.075582
4    0.405465        -0.486047
..        ...              ...
275  0.993704        -1.151185
276 -0.869053        -0.775237
277 -0.182774        -0.514966
278 -1.065133        -0.457127
279 -1.163172         1.393691

[280 rows x 2 columns]

In [67]:
X_test_scaled = pd.DataFrame(X_test_scaled, columns= X_test.columns)

In [68]:
X_test_scaled

          Age  EstimatedSalary
0   -0.771013         0.497201
1    0.013305        -0.572804
2   -0.280814         0.150172
3   -0.771013         0.265849
4   -0.280814        -0.572804
..        ...              ...
115  1.091743        -0.139018
116  0.699584         1.769639
117 -0.672973         0.555039
118  0.797624         0.352606
119  0.895664        -0.543885

[120 rows x 2 columns]

In [69]:
np.round(X_train.describe(), 1)

         Age  EstimatedSalary
count  280.0            280.0
mean    37.9          69807.1
std     10.2          34641.2
min     18.0          15000.0
25%     30.0          43000.0
50%     37.0          70500.0
75%     46.0          88000.0
max     60.0         150000.0

In [70]:
np.round(X_test.describe(), 1)

         Age  EstimatedSalary
count  120.0            120.0
mean    37.2          69591.7
std     11.1          32933.7
min     18.0          15000.0
25%     28.0          47000.0
50%     36.0          64500.0
75%     45.2          87000.0
max     60.0         150000.0