In [32]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier

In [33]:
import pandas as pd

data = pd.read_excel(r"C:\Users\Mohit Khangar\OneDrive\Desktop\AIML\IRIS\IRISTRAIN.xlsx")

data.head()

   sepallength  sepalwidth  petallength  petalwidth           class
0          7.9         3.8          6.4         2.0  Iris-virginica
1          7.7         3.8          6.7         2.2  Iris-virginica
2          7.7         3.0          6.1         2.3  Iris-virginica
3          7.7         2.8          6.7         2.0  Iris-virginica
4          7.7         2.6          6.9         2.3  Iris-virginica

In [34]:
X = data.iloc[:, :-1]  # All columns except the last as features
y = data.iloc[:, -1]   # Last column as label

In [35]:
X

     sepallength  sepalwidth  petallength  petalwidth
0            7.9         3.8          6.4         2.0
1            7.7         3.8          6.7         2.2
2            7.7         3.0          6.1         2.3
3            7.7         2.8          6.7         2.0
4            7.7         2.6          6.9         2.3
..           ...         ...          ...         ...
111          4.5         2.3          1.3         0.3
112          4.4         3.2          1.3         0.2
113          4.4         3.0          1.3         0.2
114          4.4         2.9          1.4         0.2
115          4.3         3.0          1.1         0.1

[116 rows x 4 columns]

In [37]:
y

0      Iris-virginica
1      Iris-virginica
2      Iris-virginica
3      Iris-virginica
4      Iris-virginica
            ...
111       Iris-setosa
112       Iris-setosa
113       Iris-setosa
114       Iris-setosa
115       Iris-setosa
Name: class, Length: 116, dtype: object

In [ ]:
y

In [ ]:
model = RandomForestClassifier()
model.fit(X, y)

In [ ]:
predictions = model.predict(X)  # Predict on the same/new data (for demonstration)
print(predictions)  # Display predictions

In [ ]:
import pandas as pd

dataset = pd.read_excel(r"C:\Users\Mohit Khangar\OneDrive\Desktop\AIML\IRIS\IRISTEST.xlsx")

dataset.head()

In [ ]:
x_test = dataset.iloc[:,:-1]

In [ ]:
predictions = model.predict(x_test.values)  # Predict on the same/new data (for demonstration)
print(predictions)  # Display predictions

In [38]:
predictions

array(['Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa'], dtype=object)

In [39]:
y_test = dataset.iloc[:,-1]

In [41]:
actual = y_test.values